import {useLanguage, structureName, englishSystems, englishExplanations} from './language';
import {DirectionProvider} from '@base-ui/react/direction-provider';
import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,ChevronRight,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,explanation,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
export default function Home(){
 const {language,setLanguage,t}=useLanguage();
 const name=(value:string)=>structureName(value,language);
 const systems=SYSTEMS.map(s=>({...s,...(language==='en'?englishSystems[s.id]:{})}));
 const describe=(value:string,id:SystemId)=>language==='ar'?explanation(value,id):(englishExplanations[value.toLowerCase()]??englishSystems[id].description);
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});fetch('/models/atlas.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('The anatomy catalogue could not be loaded.');return r.json();}).then(data=>setAtlas(data as Atlas)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(systems.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=systems.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=systems.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>c.name.toLowerCase().includes(term)||structureName(c.name,'ar').includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 return <DirectionProvider direction={language==='ar'?'rtl':'ltr'}><main className="studio">
  {atlas&&<AnatomyScene language={language} atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
   <header className="identity"><div className="eyebrow"><span className="status-dot"/>{t(" تشريح تفاعلي","Interactive anatomy")}</div><h1>{t("أطلس الإنسان","Human Atlas")}<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString(language):'2,234'}{t(' جزءًا نمذجيًا ',' model parts ')}<span>·</span> BodyParts3D</div></header>
   <div className="language-control"><label className="sr-only" htmlFor="atlas-language">{t("اللغة","Language")}</label><select id="atlas-language" value={language} onChange={e=>setLanguage(e.target.value as 'en'|'ar')}><option value="en" lang="en">English</option><option value="ar" lang="ar">العربية</option></select></div><nav className="top-actions" aria-label={t("لوحات الاستكشاف","Explore anatomy")}><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label={t("البحث في التشريح","Search anatomy")}><Search size={18}/><span>{t("ابحث عن بنية","Find a structure")}</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button" aria-label={t("حول هذا الأطلس","About this atlas")} onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
   <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label={t("طبقات التشريح","Anatomy layers")}>
    <div className="panel-heading"><span>{t("الأجهزة","Systems")}</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label={t("إغلاق الأجهزة","Close systems")}><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
    <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id)}))}>{t("الكل","All")}</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['skeletal']}))}>{t("العظام","Bones")}</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive']}))}>{t("الأعضاء","Organs")}</Button></div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={t(`إظهار ${s.name} فقط`,`Show only ${s.name.toLowerCase()}`)} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{s.name}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={t(`إظهار ${s.name}`,`Show ${s.name.toLowerCase()}`)} /></div>)}</div>
    <div className="panel-foot"><span>{visibleCount.toLocaleString(language)}{t(' جزء ظاهر',' visible parts')}</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>{t("إخفاء الكل","Hide all")}</Button></div>
  </section>
   {panel==='search'&&<section className="search-panel glass" aria-label={t("البحث في التشريح","Search anatomy")}><div className="panel-heading"><span>{t("ابحث عن بنية","Find a structure")}</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label={t("إغلاق البحث","Close search")}><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>name(c.name)} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder={t("القلب، الدماغ، عظم الفخذ…","Heart, femur, cranial nerve…")} aria-label={t("البحث في البنى التشريحية المسماة","Search named anatomical structures")} showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>{t("لا توجد بنى مطابقة للبحث.","No matching structures found.")}</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{name(c.name)}</span><span className="small-number">{c.elements.length} {c.elements.length===1?t('جزء','part'):t("أجزاء","parts")}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?t("تظهر حتى 80 نتيجة؛ ضيّق البحث للوصول إلى البنى الأصغر.","Showing up to 80 results. Refine your search to find smaller structures."):t("ابدأ بعضو رئيسي أو ابحث في جميع البنى المسماة.","Start with a major organ or search all named structures.")}</p></section>}
   <nav className="view-controls glass" aria-label={t("عناصر التحكم بالكاميرا","Camera controls")}>{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={t(['منظور ثلاثة أرباع','من الأمام','من الجانب','من الخلف'][i],['Three-quarter view','Front view','Side view','Back view'][i])} aria-label={t(['منظور ثلاثة أرباع','من الأمام','من الجانب','من الخلف'][i],['Three-quarter view','Front view','Side view','Back view'][i])}><span>{['¾',t("أ","F"),t("ج","S"),t("خ","B")][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?t("إيقاف الدوران","Pause rotation"):t("تدوير الجسم","Rotate body")} title={t("دوران تلقائي","Auto rotate")} className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label={t("إعادة ضبط العرض والطبقات","Reset view and layers")} title={t("إعادة ضبط","Reset")} onClick={reset}><RotateCcw size={17}/></Button></nav>
   <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?((chosen?name(chosen.name):undefined)??t("البنية المحددة","Selected structure")):state.explode>.95?t("المخزون التشريحي","Anatomical inventory"):state.explode>.05?t("البنى المفصولة","Separated structures"):t("بالغ · مرجع ذكوري","Adult \u00b7 Male reference")}</span><span className="caption-line"/></div>
   <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label={t("فتح طبقات الأجهزة","Open system layers")}><Layers3 size={20}/><span>{t("الأجهزة","Systems")}</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">{t("تفكيك التشريح","Explode anatomy")}</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>{t("مجمع","Assembled")}</span><span>{t("كل جزء","Every part")}</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label={t("تجميع وإعادة ضبط","Assemble and reset")}><RotateCcw size={18}/><span>{t("ضبط","Reset")}</span></Button></div>
   <footer className="studio-footer"><span>{state.explode>.8?t("اسحب للتحريك","Drag to pan"):t("اسحب للدوران","Drag to rotate")} <b>·</b>{t(" قرّب بإصبعين أو عجلة الفأرة "," Pinch or scroll to zoom ")}<b>·</b>{t(" اضغط للفحص"," Tap to inspect")}</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>{t("المصدر والإسناد ","Source and attribution ")}<ArrowUpRight size={12}/></Button></footer>
   {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>{t("جارٍ تجهيز التشريح","Preparing anatomy")}</strong><span>{progress}% · {t("تحميل ","Loading ")}{atlas?.parts.length.toLocaleString(language)??'2,234'} {t("جزء","parts")}</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
   {error&&<div className="loading glass error" role="alert"><p>{t("تعذر تحميل التشريح. يرجى إعادة المحاولة.","Unable to load the anatomy. Please try again.")}</p><Button variant="ghost" onClick={()=>location.reload()}>{t("إعادة تحميل العارض","Reload viewer")}</Button></div>}
   <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent closeLabel={t("إغلاق","Close")} initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?.name??t("تشريح","Anatomy")}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen?name(chosen.name):''}</SheetTitle></div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{chosen&&selected?describe(chosen.name,selected.system):''}</SheetDescription>{chosen&&!EXPLANATIONS[chosen.name.toLowerCase()]&&<span className="context-note">{t("ملخص الجهاز · تم تحديد البنية من الأطلس المصدر","System overview \u00b7 Structure identified from the source atlas")}</span>}<div className="structure-meta"><span>{t("معرّف الأطلس","Atlas ID")}<strong>{chosen?.id}</strong></span><span>{t("الأجزاء المحددة","Selected parts")}<strong>{state.selected.length.toLocaleString(language)}</strong></span></div>{selectedParts.length>1&&<div className="member-list"><h3>{t("البنى المشمولة","Included structures")}</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{name(p.name)}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>{t("و ","And ")}{selectedParts.length-50}{t(" جزءًا نمذجيًا آخر."," more model parts.")}</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">{t("فتح المصدر التشريحي ","Open anatomy source ")}<ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?t("إظهار التشريح المحيط","Show surrounding anatomy"):t("عزل البنية","Isolate structure")}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>{t("إلغاء التحديد","Clear selection")}</Button></div></SheetContent></Sheet>
   <Sheet open={about} onOpenChange={setAbout}><SheetContent closeLabel={t("إغلاق","Close")} side={language==='ar'?'left':'right'} className="about-sheet glass"><div className="eyebrow">{t("المصدر والنطاق","Source and scope")}</div><SheetTitle className="structure-title">{t("الجسم كما لم تره من قبل.","The body, seen anew.")}</SheetTitle><SheetDescription>{t("استكشف المرجع التشريحي لذكر بالغ من BodyParts3D.","Explore the adult male anatomical reference from BodyParts3D.")}</SheetDescription><div className="about-copy"><p><strong>{t("ذكر · BodyParts3D","Male \u00b7 BodyParts3D")}</strong><br/>{t("2,234 شبكة مستقلة و3,432 مفهومًا تشريحيًا مسمى من مرجع لذكر بالغ.","2,234 individual meshes and 3,432 named anatomical concepts from an adult male reference.")}</p><p>{t("لا يمثل هذا المرجع كل بنية أو اختلاف تشريحي بشري. قد يحتوي المفهوم المسمى على عدة أجزاء، بينما تُعرض كل شبكة مصدر مرة واحدة.","This reference does not represent every human structure or anatomical variation. A named concept may include several parts, while each source mesh is displayed once.")}</p><p>{t("صُممت الألوان وتجميعات الأجهزة للاستكشاف. بُسّطت الهندسة لتناسب الويب، وتقدم الشروحات سياقًا تعليميًا عامًا. هذا مرجع تشريحي وليس أداة تشخيص أو جراحة.","Colors and system groupings are designed for exploration. Geometry is simplified for the web, and descriptions provide general educational context. This is an anatomical reference, not a diagnostic or surgical tool.")}</p><h3>{t("المصدر","Source")}</h3><p>{t("BodyParts3D، حقوق The Database Center for Life Science، بترخيص CC Attribution 4.0 International.","BodyParts3D, copyright The Database Center for Life Science, licensed under CC Attribution 4.0 International.")}</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">{t("ترخيص البيانات ","Data license ")}<ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">{t("الهندسة والبيانات الأصلية ","Original geometry and data ")}<ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">{t("قراءة البحث المصدر ","Read the source paper ")}<ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main></DirectionProvider>;
}
